name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    uses: ./.github/workflows/shared-java-setup.yml

  build-and-test:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        run: ./gradlew test --continue

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            build/test-results/test/TEST-*.xml

      - name: Run ktlint checks
        run: ./gradlew ktlintCheck

      - name: Run detekt analysis
        run: ./gradlew detekt
        continue-on-error: true

      - name: Upload detekt SARIF report
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: build/reports/detekt/detekt.sarif

      - name: Build project
        run: ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: ktor-app
          path: build/libs/
