name: Detekt Code Quality Check

on:
  push:
  pull_request:

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  setup:
    uses: ./.github/workflows/shared-java-setup.yml

  detekt:
    name: Detekt Check
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Run Detekt
        run: ./gradlew detekt

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: build/reports/detekt/detekt.sarif

      - name: Upload Detekt reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: detekt-reports
          path: build/reports/detekt/
