name: Detekt Code Quality Check

on:
  push:
  pull_request:

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  detekt:
    name: Detekt Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java Environment
        uses: ./.github/actions/java-setup
        with:
          java-version: "21"

      - name: Run Detekt
        run: ./gradlew detekt --continue
        continue-on-error: true

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: build/reports/detekt/detekt.sarif
        continue-on-error: true

      - name: Upload Detekt reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: detekt-reports
          path: build/reports/detekt/
