name: Super-Linter

on: push

permissions:
  contents: read
  statuses: write

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v8.0.0
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KOTLIN_KTLINT_CONFIG_FILE: .editorconfig
          FILTER_REGEX_EXCLUDE: "(gradlew|.*\\.github/workflows/.*)"
          VALIDATE_HTML_PRETTIER: false
